### PR TITLE
Language refactor / Add Service ID examples

### PR DESCRIPTION
**Pull request by janan07**
Added Service ID examples and refacotred language in the table.

Signed-off-by: Andrew Jandacek <andrew.jandacek@broadcom.com>

### CODE REVIEW

**Comment by janan07** [comment]
> These look really good @janan07 - many thanks for making these corrections. I don't see any changes here that mean that the criteria have just changed and that this PR is just typo corrections and clarifications. Can you confirm that this is the case just so we can record this as the process to update the conformance criteria in a "breaking/changing" way require a different approval path.

That is correct. These are only changes for clarification and to fix typos to make the table a bit more readable.

**Comment by jalel01** [comment]
Thank you Joe. @jmertic would appreciate your review here when you have a moment, thank you!

**Comment by Joe-Winchester** [comment]
@janan07 - this is still draft.  Are you planning to complete this PR or has this been folded into https://github.com/openmainframeproject/foundation/pull/26 ?

**Comment by Joe-Winchester** [comment]
@janan07 - a customer noticed another problem with App Framework where 11 and 12 in Web UI Non iFrame repeats the same criteria (see screen shot)

The correction is that item 12 should read
```
Apps must not pollute the global namespace with regards Javascript, HTML, and CSS. 
```
and not be a repeat of item 11.
Are you able to add this into your PR if possible so it can be merged alltogether ?

image

**Comment by janan07** [comment]
@Joe-Winchester Yes, Joe, I caught this mistake and have corrected it in this branch.

**Pull request merged**
