### PR TITLE
Remove duplicate criteria

### PR DESCRIPTION
**Pull request by balhar-jakub**
Update bullet numbering
Cleanup authentication specification

Signed-off-by: Jakub Balhar <jakub@balhar.net>

### CODE REVIEW

**Comment by balhar-jakub** [comment]
@jmertic  Is it ok for you or would you need something else from us?

**Comment by jmertic** [comment]
Hi @balhar-jakub! Since there is one material point change, I'd need approval from someone else in the TSC or Onboarding squad. @Joe-Winchester could you help?

**Comment by balhar-jakub** [comment]
I brought it to the onboarding squad channel. Thanks

**Review by Joe-Winchester — APPROVED** [review]

**Comment by Joe-Winchester** [comment]
Tks @balhar-jakub.  I approved the PR which is a good update to highlight SSO and it won't mean anyone who has a current badge would lose it.
As well as the test_evaluation_guide.md the change will need to be applied to https://github.com/openmainframeproject/foundation/blob/main/zowe_conformance/test_evaluation_guide.md which is the non table based file, and kept up to date so folks have diff history that's easier to consume and goes back to 2019 conformance.

**Comment by balhar-jakub** [comment]
@Joe-Winchester I updated the non-table guide as well.

**Pull request merged**
