### PR TITLE
Zowe v2 conformance docs

### PR DESCRIPTION
**Pull request by jp669844**
Signed-off-by: jp669844 <jan.prihoda@broadcom.com>

### CODE REVIEW

**Comment by jmertic** [comment]
Thanks for this! Can we not do a separate directory and instead apply the changes against the current versions of these docs? It's hard to see what the changes are otherwise. Thanks!

**Comment by RASakach** [comment]
@jmertic / @jp669844  :  We will need to keep the Zowe V1 Conformance program open / available for extenders who wish to be compatible with Zowe V1 LTS (for the duration of V1 maintenance timeline).  If I am understanding the ask -- if we apply the updates against the current version, in essence we are sunsetting the Zowe V1 program.    I understand the desire to showcase the changes between V1 & V1.  As a means to address this, we did produce a PDF for each program that clearly identifies the changes between the 2 programs.  Please see this as an example:  https://ibm.ent.box.com/s/rdb7zfkcxzzbiro4idat9o7xd0qig3mt

My proposal:  Separate the directories and include the PDFs in the V2 directory that showcases the "diffs" between the V1 and V2 conformance programs.

Note:  We will showcase the "diffs" within a given program throughout the lifetime of a given Vx conformance program but we do not want confuse the Vx program with the Vx+1 program.   Please let me know if we need to meet to discuss.

**Comment by jmertic** [comment]
Good points @RASakach  and we need to discuss this more. I think it's going to be really complicated if we are running two programs simultaneously.

**Comment by jp669844** [comment]
Ok, I will close this PR and open a new one with v1 files updated to v2. The independent files will be in separate PR.

**Comment by jp669844** [comment]
Here is the following [PR](https://github.com/openmainframeproject/foundation/pull/234).

**Pull request closed without merging**
